# Generated by Django 4.0.2 on 2022-02-14 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rent_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Time'),
        ),
    ]
