# Generated by Django 4.0.2 on 2022-02-14 07:42

import car_rental.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_alter_car_rent_end_time_alter_car_rent_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rent_end_time',
            field=models.DateTimeField(default=car_rental.models.get_tomorrow),
        ),
        migrations.AlterField(
            model_name='car',
            name='rent_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
